# Generated by Django 3.2.5 on 2022-01-11 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('nickname', models.CharField(auto_created=True, default='<django.db.models.fields.EmailField>', max_length=100, unique=True)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('is_superuser', models.IntegerField()),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('pet_num', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user',
            },
        ),
        migrations.CreateModel(
            name='pet',
            fields=[
                ('pet_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='NAME')),
                ('age', models.IntegerField(verbose_name='AGE')),
                ('birth', models.DateField(verbose_name='BIRTHDAY')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='OWNER')),
            ],
        ),
    ]
