# Generated by Django 3.2.5 on 2022-01-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220111_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(auto_created=True, default='Pawpier', max_length=100),
        ),
    ]
